-- Create menu_acompanantes table for multi-select acompañante recipes per meal moment
CREATE TABLE menu_acompanantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_id BIGINT NOT NULL REFERENCES days(id) ON DELETE CASCADE,
  moment_id BIGINT NOT NULL REFERENCES moment(id) ON DELETE CASCADE,
  recipe_id BIGINT NOT NULL REFERENCES recipes(id) ON DELETE CASCADE
);

-- Insert the new "Acompañante" recipe type (id=5)
INSERT INTO types (id, name, description)
VALUES (5, 'Acompañante', 'Receta para acompañar el plato principal');
